### ISSUE TITLE
Consider aerialways and piste:type

### ISSUE THREAD

**Issue by martinstingl** [archie83/osm-strava#1]
Many false positives are generated because aerialway=* and piste:type=* are not taken into account.

**Comment by archie83** [comment]
Could you give an example for each case ?

**Comment by martinstingl** [comment]
I got false positives along these ways:
aerialway: https://www.openstreetmap.org/way/4827514
piste:type: https://www.openstreetmap.org/way/924357720

**Comment by ravenfeld** [comment]
I'm all for aerialways, but not for piste:type=*, because they often highway=track

**Comment by archie83** [comment]
I explained the problem in my [diary](https://www.openstreetmap.org/user/jcr83/diary): Sometimes, people select a wrong activity when they send their GPS tracks to Strava. The program strava.py analyzes the "run" heat maps, so these false positives shouldn't occur.

**Comment by archie83** [comment]
- there can be paths under the aerial ways.
- in summer, some paths can be close to winter pistes.

So considering these elements would lead to miss some paths.
