### ISSUE TITLE
not all leisure ways are areas

### ISSUE THREAD

**Issue by Luzandro** [archie83/osm-strava#2]
I stumbled upon a few cases, where narrow sport tracks were correctly mapped as ways with leisure=track, which led to false positives, because every object with key "leisure" is considered an area. I've therefore changed the condition to

`if (tag.attrib["k"] == "area" and tag.attrib["v"] == "yes") or (tag.attrib["k"] == "leisure" and tag.attrib["v"] != "track"):`

see also https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtrack#Areas

>  Often mapping tracks as a [way](https://wiki.openstreetmap.org/wiki/Way) way means looping back to the start, forming a [closed way](https://wiki.openstreetmap.org/wiki/Closed_way) closed way (the shape of many racetracks). It is tricky as this tag is also being tagged as an [area](https://wiki.openstreetmap.org/wiki/Area) - that can also be represented by closed ways.
> It's unclear/undecided whether closed ways should be treated as areas for this tag so it is advised to always add an [area](https://wiki.openstreetmap.org/wiki/Key:area)=yes/no tag in the case of closed ways. The default OSM Carto stylesheet displays an [area](https://wiki.openstreetmap.org/wiki/Key:area) only if area=yes is present. This is not necessary for [multipolygons](https://wiki.openstreetmap.org/wiki/Multipolygon) since they are always handled as areas.

**Comment by archie83** [comment]
I am not sure I understand. Please can you give me an example of such a false positive?

**Comment by Luzandro** [comment]
see here for an example: https://maproulette.org/challenge/42963/task/210359621

As it's treated as area, it's missing the additional plot_circle and the tile looks like this
![test_15_17869_11372_area](https://github.com/archie83/osm-strava/assets/25511512/8f8a4d7c-0cbc-4966-9a9b-9d76698a3912)

instead of this

![test_15_17869_11372_way](https://github.com/archie83/osm-strava/assets/25511512/2da25080-3e50-4ab9-8587-41abd8474486)

and therefore creates a task, which wouldn't be the case if it was treated like other ways

The difference is bigger for ways that aren't closed and therefore obviously can't be areas. At first I didn't think much about it if there are false positives near a sports area, but the case that got my attention to investigate this further was this sled run: https://www.openstreetmap.org/way/817771591
While it seems like this is tagged wrong and should only be highway=track and piste:type=sled, but not also leisure=track and sport=toboggan, I was still wondering, why this lead to so many tasks along the way, which shouldn't be the case if it was a normal highway=track.

Tiles in this case:

![test_15_17485_11470_area](https://github.com/archie83/osm-strava/assets/25511512/53ffe6a7-865e-4102-b000-57698f6b5377)

vs

![test_15_17485_11470_way](https://github.com/archie83/osm-strava/assets/25511512/aa347ef1-5104-45ec-ab9f-0a7d453b0e8f)

**Comment by archie83** [comment]
Sorry, but leisure=track is treated as a way, not an area :
```
{'id': '1231438711'}
{'k': 'area', 'v': 'no'}
{'k': 'leisure', 'v': 'track'}
{'k': 'surface', 'v': 'woodchips'}
area= False
```

```
{'id': '817771591'}
{'k': 'highway', 'v': 'track'}
{'k': 'leisure', 'v': 'track'}
{'k': 'mtb:scale', 'v': '0'}
{'k': 'name', 'v': 'Naturrodelbahn Haagalm'}
{'k': 'piste:type', 'v': 'sled'}
{'k': 'sac_scale', 'v': 'hiking'}
{'k': 'sport', 'v': 'toboggan'}
{'k': 'tracktype', 'v': 'grade2'}
area= False
```
So I don't understand your results. But your comment showed me a bug : area=no is not taken into account.

**Comment by archie83** [comment]
I fixed the bug relative to the areas that were too small. I also made various improvements. Please test the new version, you should get less false positives.

**Comment by Luzandro** [comment]
looks good 👍
